### ISSUE TITLE
OA - Limited Access not showed

### ISSUE THREAD

**Issue by enricobonaiuti** [ilri/OpenRXV#44]
@moayadnajd please see below. We have 0 and 0 in the Access

<img width="346" alt="Screen Shot 2020-10-25 at 08 00 14" src="https://user-images.githubusercontent.com/19412079/97100864-501f4a00-1698-11eb-8c61-b6b53c99b1e0.png">
<img width="556" alt="Screen Shot 2020-10-25 at 08 00 04" src="https://user-images.githubusercontent.com/19412079/97100866-51e90d80-1698-11eb-8aca-fc5ab676f515.png">

**Comment by alanorth** [comment]
Hey @enricobonaiuti. It's probably my fault because I was cleaning up the AReS mappings (of which there were 4,000). It's way too many mappings to manage realistically (for example, you fix some values in CRPs, but you break them in authors because the mappings apply to all fields). For now I will add mappings for several variations of "Limited Access" and then force AReS to do a re-harvest ASAP.

![Screenshot_2020-10-25 OpenRXV-fs8](https://user-images.githubusercontent.com/191754/97108543-5c7ac580-16df-11eb-9b81-b9962b9c0905.png)

In the long term we should make sure the repositories are using harmonized controlled vocabularies so we don't have to rely on the mapping as much.

**Comment by enricobonaiuti** [comment]
> In the long term we should make sure the repositories are using harmonized controlled vocabularies so we don't have to rely on the mapping as much.

@alanorth ok sure. As soon as we complete the review to deposit on CGSPACE from MEL we should be well aligned in terms of control lists.

**Comment by alanorth** [comment]
Looks good now.

![Screenshot_2020-10-25 OpenRXV(1)-fs8](https://user-images.githubusercontent.com/191754/97116467-5a7c2b00-170e-11eb-96d3-d7f6706c454c.png)

Regarding controlled lists, in CGSpace we've recently adapted lower case AGROVOC subjects and title case countries and regions, so that eliminated the need for about 3,500 mappings alone! Looking forward to more metadata harmonization and future work on OpenRXV. Let's bring [CIMMYT's DSpace](https://repository.cimmyt.org) in!
